[project]
name = "timba"
version = "0.0.1"
dependencies = [
    "beautifulsoup4",
    "curlify",
    "pandas",
    "requests",
    "yfinance",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["timba", "timba.src", "timba.scraping"]
